create table public.breeds (
  id uuid primary key default gen_random_uuid(),
  species text not null,
  breed_name text not null,
  general_prompt text not null,
  is_mixed_unknown boolean not null default false,
  display_order int not null default 0,
  created_at timestamptz not null default now()
);

grant select on public.breeds to anon, authenticated;
grant all on public.breeds to service_role;

alter table public.breeds enable row level security;

create policy "breeds are publicly readable" on public.breeds
  for select using (true);

insert into public.breeds (species, breed_name, general_prompt, is_mixed_unknown, display_order) values
  ('dog', 'Labrador Retriever', 'Prone to obesity (rarely seems "full"), hip and elbow dysplasia, ear infections due to floppy ears. High energy, needs lots of exercise.', false, 1),
  ('dog', 'German Shepherd', 'Hip/spinal dysplasia, degenerative myelopathy in older dogs, bloat (gastric torsion) risk. Intelligent, needs mental stimulation.', false, 2),
  ('dog', 'Golden Retriever', 'Higher cancer rates (lymphoma, hemangiosarcoma) compared to other breeds, hip dysplasia, skin allergies.', false, 3),
  ('dog', 'French Bulldog', 'Brachycephalic syndrome (breathing difficulty, heat intolerance), skin fold infections, spinal deformities. Never overexert in heat.', false, 4),
  ('dog', 'Dachshund', 'High risk of IVDD (intervertebral disc disease) due to long spine — jumping/stairs are a risk factor. Obesity makes this worse.', false, 5),
  ('dog', 'Yorkshire Terrier', 'Tracheal collapse risk, dental crowding (small mouth), hypoglycemia in puppies.', false, 6),
  ('dog', 'Chihuahua', 'Open fontanelle in puppies, heart issues (mitral valve), dental crowding, shivering in cold/stress (normal for the breed).', false, 7),
  ('dog', 'Border Collie', 'Very high energy and intelligence — frustration/destructive behavior without enough stimulation. Some lines prone to epilepsy.', false, 8),
  ('dog', 'Beagle', 'Prone to obesity (very food-motivated), ear infections, epilepsy. Strong scent drive — prone to bolting/escaping.', false, 9),
  ('dog', 'Poodle', 'Progressive retinal atrophy (vision), Addison''s disease, needs regular trimming (hair grows continuously, doesn''t shed).', false, 10),
  ('dog', 'Mixed breed / Don''t know', 'No breed-specific predispositions — focus on age, size, body condition, and symptoms the owner describes.', true, 11),
  ('cat', 'Domestic Shorthair (most common)', 'No specific genetic predispositions — treat as a generic cat, focus on age and symptoms.', false, 1),
  ('cat', 'British Shorthair', 'Prone to obesity, hypertrophic cardiomyopathy (HCM), polycystic kidney disease in some lines.', false, 2),
  ('cat', 'Persian', 'Flat face = breathing/tearing issues, polycystic kidney disease (PKD), needs daily brushing (matted fur).', false, 3),
  ('cat', 'Maine Coon', 'Hypertrophic cardiomyopathy (HCM) — common in the breed, spinal muscular atrophy in some lines. Large breed, slow to reach adulthood (up to 3-4 years).', false, 4),
  ('cat', 'Siamese', 'Prone to dental disease, liver amyloidosis, asthma/bronchial disease. Very vocal and social breed.', false, 5),
  ('cat', 'Ragdoll', 'Hypertrophic cardiomyopathy (HCM), polycystic kidney disease. Very relaxed temperament — may hide pain/illness longer than other cats.', false, 6),
  ('cat', 'Sphynx', 'No fur = sensitive to temperature (cold/sunburn), oily skin needs regular cleaning, heart issues (HCM).', false, 7),
  ('cat', 'Scottish Fold', 'Cartilage mutation (osteochondrodysplasia) can cause painful arthritis — common in the breed, watch for joint stiffness.', false, 8),
  ('cat', 'Bengal', 'High energy, needs mental/physical stimulation. Progressive retinal atrophy in some lines.', false, 9),
  ('cat', 'Russian Blue', 'Generally healthy breed, prone to obesity if overfed (very food-motivated).', false, 10),
  ('cat', 'Mixed breed / Don''t know', 'No breed-specific predispositions — focus on age, body condition, and symptoms.', true, 11),
  ('rabbit', 'Holland Lop', 'Floppy ears = prone to ear infections, dental malocclusion (short skull).', false, 1),
  ('rabbit', 'Netherland Dwarf', 'Very small breed — fast metabolism, sensitive to incorrect diet (too many carbs = GI stasis).', false, 2),
  ('rabbit', 'Mini Rex', 'Sensitive skin on paws (sore hocks) due to thin fur, otherwise generally healthy.', false, 3),
  ('rabbit', 'Lionhead', 'Long fur around head/neck — prone to matting and fly strike in summer, regular brushing required.', false, 4),
  ('rabbit', 'Dutch', 'Generally healthy, medium-sized breed — standard rabbit health profile (teeth, GI, mobility).', false, 5),
  ('rabbit', 'Mixed breed / Don''t know', 'Generic rabbit profile — focus on teeth, diet, GI motility, and signs of pain.', true, 6),
  ('bird', 'Budgerigar (Budgie)', 'Prone to tumors (especially females), obesity from seed-only diets, needs social interaction/enrichment.', false, 1),
  ('bird', 'Cockatiel', 'Prone to calcium/vitamin D deficiency on poor diets, "night frights" (panic at night), respiratory infections.', false, 2),
  ('bird', 'Lovebird', 'Territorial/aggressive behavior in some individuals, prone to feather plucking under stress.', false, 3),
  ('bird', 'Canary', 'Sensitive to temperature changes and drafts, respiratory issues, loud singing (males) is normal.', false, 4),
  ('bird', 'African Grey Parrot', 'Very high intelligence — behavioral problems (feather plucking, screaming) without enough stimulation. Long lifespan (40-60 years), calcium deficiency common.', false, 5),
  ('bird', 'Mixed breed / Don''t know', 'Generic bird profile — focus on feathers, breathing, diet, and behavioral signs of stress.', true, 6),
  ('fish', 'Goldfish', 'Produce a lot of waste — needs strong filtration, prone to swim bladder problems from overfeeding.', false, 1),
  ('fish', 'Betta (Siamese fighting fish)', 'Territorial, must not be housed with other bettas, prone to fin rot in poor water quality.', false, 2),
  ('fish', 'Guppy', 'Very prolific (breed quickly), generally hardy, sensitive to temperature swings.', false, 3),
  ('fish', 'Neon Tetra', 'Sensitive to water quality, "Neon Tetra Disease" (parasitic) is common and incurable.', false, 4),
  ('fish', 'Angelfish', 'Territorial in pairs/breeding, need a taller tank (tall fins), sensitive to ammonia spikes.', false, 5),
  ('fish', 'Mixed breed / Don''t know', 'Generic fish profile — focus on water parameters, behavior, and visible signs of illness (fins, scales).', true, 6),
  ('hamster', 'Syrian Hamster', 'Must live ALONE (territorial, will kill other hamsters in the same space), prone to "wet tail" (stress diarrhea) in young hamsters.', false, 1),
  ('hamster', 'Campbell''s Dwarf', 'Can live in pairs/groups (unlike Syrian), prone to diabetes — watch sugary food/fruit.', false, 2),
  ('hamster', 'Winter White Dwarf', 'Similar to Campbell''s, changes coat color in winter under low light, prone to diabetes.', false, 3),
  ('hamster', 'Roborovski Hamster', 'Smallest and fastest — hard to handle, mostly an observation pet, generally healthy.', false, 4),
  ('hamster', 'Chinese Hamster', 'Mouse-like shape, can live in pairs, prone to diabetes like other dwarf hamsters.', false, 5),
  ('hamster', 'Mixed breed / Don''t know', 'Generic hamster profile — focus on diet, social needs (solo vs. group), and signs of stress.', true, 6),
  ('guinea_pig', 'American (Short-haired)', 'Most common breed, generally healthy, standard guinea pig profile (vitamin C is essential, they can''t synthesize it).', false, 1),
  ('guinea_pig', 'Abyssinian', 'Rosettes in fur (swirl patterns) — prone to matting, otherwise healthy breed.', false, 2),
  ('guinea_pig', 'Peruvian', 'Very long fur — high maintenance (daily brushing), risk of overheating in summer.', false, 3),
  ('guinea_pig', 'Silkie/Sheltie', 'Long fur without rosettes — similar maintenance to Peruvian, but simpler.', false, 4),
  ('guinea_pig', 'Teddy', 'Short, dense, curly fur — low maintenance, generally healthy.', false, 5),
  ('guinea_pig', 'Mixed breed / Don''t know', 'Generic guinea pig profile — focus on vitamin C intake, teeth, and signs of pain.', true, 6),
  ('turtle', 'Red-Eared Slider', 'Most common pet aquatic turtle — needs UVB lighting, prone to respiratory infections at low water temperature.', false, 1),
  ('turtle', 'Box Turtle', 'Terrestrial, needs humid environment (not too dry), prone to respiratory infections and vitamin A deficiency.', false, 2),
  ('turtle', 'Russian Tortoise', 'Terrestrial, needs a dry environment and a high-fiber diet, prone to shell rot from excess moisture.', false, 3),
  ('turtle', 'Painted Turtle', 'Aquatic, similar to red-eared slider, needs UVB and clean water.', false, 4),
  ('turtle', 'Greek Tortoise', 'Similar to Russian Tortoise — dry environment, plant-based diet, slow growth.', false, 5),
  ('turtle', 'Mixed breed / Don''t know', 'Generic turtle/tortoise profile — focus on UVB/temperature, shell health, and diet.', true, 6),
  ('snake', 'Ball Python', 'Very popular beginner snake, prone to respiratory infections at low humidity, may refuse food (normal, not always illness).', false, 1),
  ('snake', 'Corn Snake', 'Hardy, good for beginners, generally healthy with proper temperature/humidity.', false, 2),
  ('snake', 'King Snake', 'Generally healthy, needs separate housing (cannibalistic toward other snakes).', false, 3),
  ('snake', 'Boa Constrictor', 'Large breed (up to 3m) — needs a lot of space, prone to respiratory infections, inclusion body disease (serious viral illness).', false, 4),
  ('snake', 'Hognose Snake', 'Smaller breed, dramatic "playing dead" behavior is normal (not necessarily illness), generally hardy.', false, 5),
  ('snake', 'Mixed breed / Don''t know', 'Generic snake profile — focus on enclosure temperature/humidity, feeding, and skin condition.', true, 6),
  ('lizard', 'Bearded Dragon', 'Very popular, prone to metabolic bone disease (MBD) without enough UVB/calcium, impaction from wrong substrate.', false, 1),
  ('lizard', 'Leopard Gecko', 'Nocturnal, doesn''t need UVB as urgently as diurnal species, prone to MBD if diet isn''t calcium-balanced.', false, 2),
  ('lizard', 'Crested Gecko', 'Nocturnal, doesn''t strictly need UVB, diet mostly fruit-powder based — watch for dehydration.', false, 3),
  ('lizard', 'Blue-Tongued Skink', 'Omnivore, needs a varied diet, prone to obesity from too much protein/too little exercise.', false, 4),
  ('lizard', 'Green Anole', 'Small, fast, needs high humidity, shorter lifespan than other lizards.', false, 5),
  ('lizard', 'Mixed breed / Don''t know', 'Generic lizard profile — focus on UVB/calcium, humidity, and signs of MBD (soft bones, tremors).', true, 6),
  ('spider', 'Chilean Rose Hair Tarantula', 'Very popular beginner tarantula, calm temperament, can go long periods without eating (normal, not necessarily illness).', false, 1),
  ('spider', 'Mexican Red Knee Tarantula', 'Calm temperament, long-lived (females up to 30 years), standard humidity/temperature care.', false, 2),
  ('spider', 'Curly Hair Tarantula', 'Hardy, forgiving of care mistakes, good for beginners.', false, 3),
  ('spider', 'Pink Toe Tarantula', 'Arboreal (lives on branches, not in burrows) — needs a tall enclosure, faster than terrestrial species.', false, 4),
  ('spider', 'Brazilian Black Tarantula', 'Very calm temperament, long-lived, standard care.', false, 5),
  ('spider', 'Mixed breed / Don''t know', 'Generic spider/tarantula profile — focus on the molting cycle, humidity, and signs of stress (web spinning, refusing food).', true, 6);